apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-cicd-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-cicd-pipeline
  template:
    metadata:
      labels:
        app: example-cicd-pipeline
    spec:
      containers:
      - name: example-cicd-pipeline
        image: example-cicd-pipeline:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-cicd-service
spec:
  selector:
    app: example-cicd-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
