name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Run tests
      run: pytest src/tests

    - name: Lint code
      run: pip install flake8 && flake8 src/

    - name: Build Docker image
      run: docker build -t example-cicd-pipeline .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Deploy to Minikube
      run: |
        minikube start
        eval $(minikube -p minikube docker-env)
        docker build -t example-cicd-pipeline .
        kubectl apply -f k8s/deployment.yaml
